[2023-07-09T05:51:50.676+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: product_etl_dag.extract_load_src.load_src_data manual__2023-07-09T05:51:44.852048+00:00 [queued]>
[2023-07-09T05:51:50.693+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: product_etl_dag.extract_load_src.load_src_data manual__2023-07-09T05:51:44.852048+00:00 [queued]>
[2023-07-09T05:51:50.694+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-09T05:51:50.747+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): extract_load_src.load_src_data> on 2023-07-09 05:51:44.852048+00:00
[2023-07-09T05:51:50.756+0000] {standard_task_runner.py:57} INFO - Started process 863 to run task
[2023-07-09T05:51:50.760+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'product_etl_dag', 'extract_load_src.load_src_data', 'manual__2023-07-09T05:51:44.852048+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp4vqnb438']
[2023-07-09T05:51:50.761+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask extract_load_src.load_src_data
[2023-07-09T05:51:50.845+0000] {task_command.py:410} INFO - Running <TaskInstance: product_etl_dag.extract_load_src.load_src_data manual__2023-07-09T05:51:44.852048+00:00 [running]> on host 5865fe7b5e5b
[2023-07-09T05:51:50.972+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='product_etl_dag' AIRFLOW_CTX_TASK_ID='extract_load_src.load_src_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T05:51:44.852048+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-09T05:51:44.852048+00:00'
[2023-07-09T05:51:50.998+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 24, in load_src_data
    conn = BaseHook.get_connection('mysql_connection')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_connection` isn't defined
[2023-07-09T05:51:51.007+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=product_etl_dag, task_id=extract_load_src.load_src_data, execution_date=20230709T055144, start_date=20230709T055150, end_date=20230709T055151
[2023-07-09T05:51:51.023+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 14 for task extract_load_src.load_src_data (The conn_id `mysql_connection` isn't defined; 863)
[2023-07-09T05:51:51.052+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-09T05:51:51.097+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
