[2023-07-09T08:47:19.244+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract_data manual__2023-07-09T08:47:16.176940+00:00 [queued]>
[2023-07-09T08:47:19.256+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract_data manual__2023-07-09T08:47:16.176940+00:00 [queued]>
[2023-07-09T08:47:19.257+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-09T08:47:19.275+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data> on 2023-07-09 08:47:16.176940+00:00
[2023-07-09T08:47:19.282+0000] {standard_task_runner.py:57} INFO - Started process 3037 to run task
[2023-07-09T08:47:19.285+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'extract_data', 'manual__2023-07-09T08:47:16.176940+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpmvazdanq']
[2023-07-09T08:47:19.286+0000] {standard_task_runner.py:85} INFO - Job 123: Subtask extract_data
[2023-07-09T08:47:19.331+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_dag.extract_data manual__2023-07-09T08:47:16.176940+00:00 [running]> on host 5865fe7b5e5b
[2023-07-09T08:47:19.430+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T08:47:16.176940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-09T08:47:16.176940+00:00'
[2023-07-09T08:47:19.441+0000] {base.py:73} INFO - Using connection ID 'testsql' for task execution.
[2023-07-09T08:47:19.457+0000] {logging_mixin.py:149} INFO - ================================
[2023-07-09T08:47:19.458+0000] {logging_mixin.py:149} INFO - 0     
1     
2     
3     
4     
5     
6     
7     
8     
9     
10    
11    
12    
13    
14    
15    
16    
17    
18    
Name: Response, dtype: object
[2023-07-09T08:47:19.459+0000] {logging_mixin.py:149} INFO - ================================
[2023-07-09T08:47:19.459+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 19, in extract
    for index, row in 3:
TypeError: 'int' object is not iterable
[2023-07-09T08:47:19.471+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=extract_data, execution_date=20230709T084716, start_date=20230709T084719, end_date=20230709T084719
[2023-07-09T08:47:19.485+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 123 for task extract_data ('int' object is not iterable; 3037)
[2023-07-09T08:47:19.497+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-09T08:47:19.527+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
